    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub UdaPeople-${ID}
      GroupDescription: Allow port 22 and port 3030.
      GroupDescription: Allow port 9100, 22 and port 3030.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
@@ -20,6 +20,10 @@ Resources:
          FromPort: 3030
          ToPort: 3030
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9100
          ToPort: 9100
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
@@ -31,4 +35,6 @@ Resources:
      ImageId: ami-0c4f7023847b90238
      Tags:
        - Key: Name
          Value: !Sub backend-${ID} 
          Value: !Sub backend-${ID}
        - Key: Project
          Value: Udapeople 